// pages/[slug].vue
<template>
  <component :is="currentComponent" v-if="wedding" :data="wedding" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, createError } from '#app'
import weddingsData from '~/data/weddings.json'
import type { WeddingData } from '~/types/wedding'
import ElegantForestTheme from '~/components/Themes/ElegantForest.vue'
import SketchyModernTheme from '~/components/Themes/SketchyModern.vue'

const route = useRoute()
const slug = route.params.slug as string

const wedding = computed(() => {
  return (weddingsData.weddings as WeddingData[]).find((w) => w.slug === slug)
})

if (!wedding.value) {
  throw createError({ statusCode: 404, statusMessage: 'Page Not Found', fatal: true })
}

const currentComponent = computed(() => {
  switch (wedding.value?.theme) {
    case 'elegant-forest':
      return ElegantForestTheme
    case 'sketchy-modern':
      return SketchyModernTheme
    default:
      return ElegantForestTheme
  }
})
</script>

// app/[slug]/page.tsx
import { notFound } from 'next/navigation'
import weddingsData from '@/data/weddings.json'
import { WeddingData } from '@/types/wedding'
import { ElegantForestTheme } from '@/components/Themes/ElegantForest'
import { SketchyModernTheme } from '@/components/Themes/SketchyModern'

interface PageProps {
  params: {
    slug: string
  }
}

export async function generateStaticParams() {
  return (weddingsData.weddings as WeddingData[]).map((wedding) => ({
    slug: wedding.slug,
  }))
}

export default async function WeddingPage({ params }: PageProps) {
  const { slug } = await params
  const wedding = (weddingsData.weddings as WeddingData[]).find(
    (w) => w.slug === slug
  )

  if (!wedding) {
    notFound()
  }

  // Theme Switcher Logic
  switch (wedding.theme) {
    case 'elegant-forest':
      return <ElegantForestTheme data={wedding} />
    case 'sketchy-modern':
      return <SketchyModernTheme data={wedding} />
    default:
      return <ElegantForestTheme data={wedding} />
  }
}
